import datetime
import os
import pprint
import re
import shutil
import sys
import traceback

from contextlib import contextmanager

import tank
from tank.platform.qt import QtCore, QtGui
from .playblast_dialog import PlayblastDialog

import pymel.core as pm
import maya.cmds as cmds
import maya.mel as mel

class PlayblastManager(object):
    __uploadToShotgun = True

    """
    Main playblast functionality
    """
    def __init__(self, app, context=None):
        """
        Construction
        """
        self._app = app
        self._context = context if context else self._app.context

    def showDialog(self):
        try:
            self._app.engine.show_dialog("Playblast %s" % self._app.version,
                                         self._app, PlayblastDialog, self._app, self)
        except:
            traceback.print_exc()

    def doPlayblast(self, **overridePlayblastParams):
        template_work = self._app.get_template("template_work")
        template_shot = self._app.get_template("template_shot")
        sceneName = pm.sceneName()
        fields = template_work.get_fields(sceneName)
        self.shotPlayblastPath = template_shot.apply_fields(fields)

        # set local path on C:\Temp
        localDir = r"C:\Temp"
        # make sure it is exists
        if not os.path.isdir(localDir):
            os.mkdir(localDir)
        # use the basename of generated names
        self.localPlayblastPath = os.path.join(localDir, os.path.basename(self.shotPlayblastPath))
        # run actual playblast routine
        self.__createPlayblast(**overridePlayblastParams)
        self._app.log_info("Playblast for %s succesful" % sceneName)
        
    def __createPlayblast(self, **overridePlayblastParams):
        localPlayblastPath = self.localPlayblastPath
        
        # setting playback range
        originalPlaybackRange = ( pm.playbackOptions( query=True, minTime=True ), 
                                  pm.playbackOptions( query=True, maxTime=True ))
        startTime = pm.playbackOptions( query=True, animationStartTime=True )
        endTime = pm.playbackOptions( query=True, animationEndTime=True )
        pm.playbackOptions( edit=True, minTime=startTime, maxTime=endTime )
        
        # get playblast parameters from hook
        playblastParams = self._app.execute_hook("hook_setup_window", action="playblast_params", data=localPlayblastPath)
        # get window and editor parameters from hook
        createWindow = self._app.execute_hook("hook_setup_window", action='create_window')

        # with the created window, do a playblast
        with createWindow():
            playblastParams.update(overridePlayblastParams)
            playblastSuccessful = False
            while not playblastSuccessful:
                try:
                    # set required visibleHUDs from hook
                    visibleHUDs = self._app.execute_hook("hook_setup_window", action="hud_set")

                    resultPlayblastPath = pm.playblast( **playblastParams )
                    playblastSuccessful = True
                except RuntimeError, e:
                    result = QtGui.QMessageBox.critical(None, u"Playblast Error",
                                                        "%s\n\n... or just close your QuickTime player, and Retry." % unicode(e),
                                                        QtGui.QMessageBox.Retry | QtGui.QMessageBox.Abort)
                    if result==QtGui.QMessageBox.Abort:
                        self._app.log_error("Playblast aborted")
                        return
                finally:
                    # restore HUD state
                    self._app.execute_hook("hook_setup_window", action="hud_unset", data=visibleHUDs)
                    # restore playback range
                    originalMinTime, originalMaxTime = originalPlaybackRange
                    pm.playbackOptions( edit=True, minTime=originalMinTime, maxTime=originalMaxTime )

        # do post playblast process, copy files and other necessary stuff
        result = self._app.execute_hook("hook_post_playblast", action="copy_file", data=localPlayblastPath)
        
        if result:
            self._app.log_info("Playblast local file created: %s" % localPlayblastPath)

        playblast_movie = self.shotPlayblastPath
        project = self._app.context.project
        entity = self._app.context.entity
        task = self._app.context.task

        data = { 'project': project,
                 'code': os.path.basename(playblast_movie),
                 'description': 'automatic generated by playblast app',
                 'sg_path_to_movie': playblast_movie,
                 'entity': entity,
                 'sg_task': task,
                 'user': {'type':'HumanUser', 'id':38} 
               }
        self._app.log_debug("Version-creation hook data:\n" + pprint.pformat(data))
        result = self._app.execute_hook("hook_post_playblast", action="create_version", data=data)
        self._app.log_debug("Version-creation hook result:\n" + pprint.pformat(result))

        if result and self.__uploadToShotgun:
            result = self._app.execute_hook("hook_post_playblast", action="upload_movie",
                                            data=dict(path=data["sg_path_to_movie"],
                                                      project=project,
                                                      version_id=result["id"]))

        self._app.log_info("Playblast finished")

    def setUploadToShotgun(self, value):
        self._app.log_debug("Upload to Shotgun set to %s" % value)
        self.__uploadToShotgun = value
